app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    author = db.Column(db.String(250))
    email = db.Column(db.String(250), unique=True, index=True)
    password_hash = db.Column(db.String(250))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pitch = db.relationship('Pitches', backref='author', lazy='dynamic')
    comments = db.relationship('Comments', backref='author', lazy='dynamic')
                                   
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'User {self.author}'

class Pitches(db.Model):
    __tablename__ = 'pitches'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(250))
    category = db.Column(db.String(250))
    pitch = db.Column(db.String(250))
    date = db.Column(db.DateTime(250), default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    comments = db.relationship('Comments', backref='title', lazy='dynamic')
    
    def save_pitch(self):
        db.session.add(self)
        db.session.commit()
        
    @classmethod
    def get_pitches(cls,cate):
        pitch = Pitches.query.filter_by(category=cate).all()
        return pitch
    
    @classmethod
    def get_pitches_user(cls,user_id):
        pitch = Pitches.query.filter_by(user_id=user_id).all()
        return pitch
    
    def __repr__(self):
        return f"Pitches {self.pitch}','{self.date}')"

class Comments(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(255))
    date_posted = db.Column(db.DateTime(250), default=datetime.utcnow)
    pitches_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    
    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comment(cls,id):
        comments = Comments.query.filter_by(pitches_id=id).all()
        return comments
    
    def __repr__(self):
        return f"Comments('{self.comment}', '{self.date_posted}')"

app/forms.py
# rom flask_wtf import FlaskForm
# from wtforms import StringField,TextAreaField,SubmitField
# from wtforms.validators import Required

# class PitchForm(FlaskForm):

#     title = StringField('Review title',validators=[Required()])
#     review = TextAreaField('Pitch review', validators=[Required()])
#     submit = SubmitField('Submit')

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import Required


class PitchForm(FlaskForm):
    
    title = StringField('Pitch Title')

    category = SelectField(u'Pitch category', choices=[('coding', 'coding'), ('life', 'life'), ('funny', 'funny')])
        
    pitch = TextAreaField('Pitch')

    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    title = StringField('Title')
    comment = TextAreaField('Comment')
    submit = SubmitField('Post Comments')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):
    

    app = Flask(__name__)
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    
    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # configure UploadSet
    configure_uploads(app,photos)

    # Initializing flask extensions
    Bootstrap(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)



    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,error

app/main/views.py
from flask import render_template
from flask import render_template, request, redirect, url_for
from flask_login import login_required, current_user
from ..models import Pitches, User, Comments
from . import main
from .. import db,photos
from .forms import PitchForm, CommentForm, UpdateProfile

@main.route('/')
def index():
    '''
    my index page
    return
    '''
    message = "Hello"
    title= 'Let The Pitch Out!'
    return render_template('index.html', message=message)

@main.route('/pitch/', methods=['GET', 'POST'])
@login_required
def new_pitch():

    form = PitchForm()

    if form.validate_on_submit():
        category = form.category.data
        pitch = form.pitch.data

        title=form.title.data
        
        # Updated pitchinstance
        new_pitch = Pitches(title=title,category=category, pitch=pitch,user_id=current_user.id)

        title = 'New Pitch'

        # save review method
        new_pitch.save_pitch()
        
        return redirect(url_for('main.index'))

    return render_template('pitch.html', pitch_entry=form)

@main.route('/categories/<cate>')
def category(cate):
    '''
    function to return the pitches by category
    '''
    category = Pitches.get_pitches(cate)
    # print(category)
    title = f'{cate}'
    return render_template('categories.html', title=title, category=category)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(author = uname).first()
    pitches= Pitches.query.filter_by(user_id=current_user.id).first()
    pitchdetails= Pitches.get_pitches_user(current_user.id)
    
    if user is None:
        abort(404)

    return render_template("profile/profile.html",pitches=pitches, user = user,pitchdetails=pitchdetails)

@main.route('/user/<uname>/update', methods=['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(author=uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname=user.author))

    return render_template('profile/update.html', form=form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(author = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/comments/<id>',methods=['GET','POST'])
@login_required
def comment(id):
    '''
    function to return the comments
    '''
    comment =Comments.get_comment(id)
    print(comment)
    title = 'comments'
    return render_template('comments.html',comment = comment)

@main.route('/new_comment/<id>', methods = ['GET', 'POST'])
@login_required
def new_comment(id):
    form = CommentForm()
    pitch=Pitches.query.filter_by(id=id).first()
    cate=pitch.category
    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comments(comment=comment,pitches_id=id,user_id=current_user.id)
        new_comment.save_comment()
        return redirect(url_for('main.category',cate=cate))

    title = 'New Comment'
    return render_template('new_comment.html', title = title, comment_form = form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block navbar%}

    {% include 'navbar.html' %}

{% endblock %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
 <head>
   <meta charset="utf-8">
   {% if title %}
   <title>{{ title }}</title>
   {% else %}
   <title>Let The Pitch Out!! </title>
   {% endif %}
 </head>
 <body>

   {% block content %}

   {% endblock %}

 </body>
</html>

app/templates/categories.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/categories.css')}}"> {% endblock %}
<br>
<br>
<br>
<br>

<body style="background-color: aliceblue;">
    {% block content %}
    <br>
    <br>
    <button type="button" class="btn btn-outline-primary" style="margin-left: 29.4%;"><a href="../pitch/">Add Pitch</a></button>
    <div class="container" style="width:400px; text-align: center;">
        <div class="card-columns">
            {% for category in category %}

            <div class="card bg-transparent border-success" style="border-style: solid; border-color: rgb(79, 188, 196); border-width:thin;">
                <div class="card-header bg-transparent border-success">
                    {{category.title}}
                </div>
                <div class="card-body text">
                    <blockquote class="blockquote mb-0">
                        <p>{{category.pitch}}</p><br>
                        <footer class="blockquote-footer bg-transparent border-success">{{category.author}}
                            <br><cite title="Source Title">Publish date: {{category.date.strftime('%Y-%m-%d')}}</cite>
                        </footer>
                    </blockquote>
                </div>
                <div class="card-footer bg-transparent border-success">
                    <button type="button" class="btn btn-outline-success btn-sm"><a href="/new_comment/{{category.id}}">Comment</a></button> <button type="button" class="btn btn-outline-success btn-sm"><a href="/comments/{{category.id}}">View comments</a></button>
                </div>
                    </button>
                </div>
            </div>
            <br>

            {% endfor %}

        </div>
        
        {% endblock %}
</body>

app/templates/comments.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<br>
<br>

<body style="background-color: aliceblue;">
    {% for comm in comment %}
    <div class="card border-info mb-3" style="max-width: 35rem;border-style: solid; border-color: rgb(79, 188, 196); border-width:thin; text-align: center; margin-left: 35%">
        <div class="card-header" style="border-style: solid;border-width:thin; border-color: rgb(79, 188, 196);">{{comm.author}}</div>
            <div class="card-body text-info">
                <p class="card-text">{{comm.comment}}.</p>
            </div>
            <div class="card-footer bg-transparent border-success"><small class="text-muted">Publish date:{{comm.date_posted.strftime('%Y-%m-%d')}}</small>
            </div>
    </div>
    <br>

    {% endfor %}

    {% endblock %}
</body>

app/templates/fourOhfour.html
{% extends 'base.html'%}

{% block content%}

    <h1>Sorry! we can't find that page</h1>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<body style="background-color: aliceblue;">
    <br>
    <br>
    <div class="container-fluid" style="text-align: center; margin-left: 35%;">
        <div class="card-groups">
            <!-- <div class="card"> --> 
            <div class="card border-info mb-3" style="max-width: 35rem;border-style: solid; border-color: rgb(79, 188, 196); border-width:thin;">
                <div class="card-header" style="border-style: solid;border-width:thin; border-color: rgb(79, 188, 196);">Coding</div>
                <div class="card-body text-info">
                    <h5 class="card-title">Pitches about coding</h5>
                    <p class="card-text">Want to change peoples mindsets, then give a pitch on best coding practices!!</p>
                    <button type="button" class="btn btn-outline-primary"><a href="../pitch/">Add Pitch</a></button>
                    <button type="button" class="btn btn-outline-primary"><a href="/categories/coding">Read Pitches</a></button>
                </div>
            </div>
            <br>
            <div class="card border-info mb-3" style="max-width: 35rem;border-style: solid; border-color: rgb(79, 188, 196); border-width:thin;">
                <div class="card-header" style="border-style: solid;border-width:thin; border-color: rgb(79, 188, 196);">Life</div>
                <div class="card-body text-info">
                    <h5 class="card-title">Pitches about life</h5>
                    <p class="card-text">Want to change peoples mindsets, then give a pitch on best life practices!!</p>
                    <button type="button" class="btn btn-outline-primary"><a href="../pitch/">Add Pitch</a></button>
                    <button type="button" class="btn btn-outline-primary"><a href="/categories/life">Read Pitches</a></button>
                </div>
            </div>
            <br>
            <div class="card border-info mb-3" style="max-width: 35rem;border-style: solid; border-color: rgb(79, 188, 196); border-width:thin;">
                <div class="card-header" style="border-style: solid;border-width:thin; border-color: rgb(79, 188, 196);">Funny</div>
                <div class="card-body text-info">
                    <h5 class="card-title">Funny Pitches</h5>
                    <p class="card-text">Want to change peoples mindsets, then give a pitch on how best to make things fun!!</p>
                    <button type="button" class="btn btn-outline-primary"><a href="../pitch/">Add Pitch</a></button>
                    <button type="button" class="btn btn-outline-primary"><a href="/categories/funny">Read Pitches</a></button>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</body>

app/templates/navbar.html
<nav class="navbar navbar-inverse" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Let The Pitch Out</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
            <li><a class="nav-link" href="/"><span class="sr-only">(current)</span>Home</a></li>
            <li>
                <a class="nav-link" href="/categories/coding">Coding</a>
            </li>
                <li>
                <a class="nav-link" href="/categories/life">Life</a>
                <li>
                <a class="nav-link" href="/categories/funny">Funny</a>
            </li>
            </ul>
           
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{url_for('main.profile',uname=current_user.author)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
        </div>
    </div>
</nav>

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<br>
<br>
<div class="container" style="background-color: aliceblue;">
<br>
<br>
  {{ wtf.quick_form(comment_form) }}


</div>



{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<br>
<br>
<div class="container" style="background-color: aliceblue;">
<br>
<br>
  {{ wtf.quick_form(pitch_entry) }}

</div>



{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
{% if user == current_user %}

{% endif %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">

            <h3> {{user.author| capitalize}} </h3>
            <br>
            <hr>
            <a href="{{url_for('main.update_profile',uname=user.author)}}">Edit profile</a>
            <!--Displaying user bio-->
            {% if user.bio %}

            <br>
            <h4> {{user.bio}}</h4>

            {%else%}
            <br>
            <p> {{user.author| capitalize}} has no bio </p>

            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-8">

            {% if user.profile_pic_path %}

            <div class="card">
                <img class="card" src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" width="150px" height="150px">
            </div>

            <div class="row">

            {%else%}
            <h3><strong>No profile picture</strong></h3>

            {% endif %}

            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.author)}}" method="post" enctype="multipart/form-data">

                <br>
                <input type="file" name="photo" class="form-control" required>
                <br>
                <input type="submit">

            </form>
            <br>
            {% endif %}

            {% for pitch in pitchdetails %}
            <div class="card border-info mb-3" style="max-width: 35rem;border-style: solid; border-color: rgb(79, 188, 196); border-width:thin; text-align: center;">
                <div class="card-header" style="border-style: solid;border-width:thin; border-color: rgb(79, 188, 196);">{{pitch.category}}</div>
                    <div class="card-body text-info">
                        <h3>{{pitch.pitch}}</h3>
                    </div>
                </div>
            
            <br>    
            {% endfor %}




        </div>
    </div>
    {% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}